export const mockImmeubles = [
  {
    id: "im_1",
    name: "Résidence Les Jardins",
    address: "15 Rue de la Paix",
    city: "Paris",
    apartmentCount: 24,
  },
  {
    id: "im_2",
    name: "Immeuble Bellevue",
    address: "8 Avenue Victor Hugo",
    city: "Lyon",
    apartmentCount: 18,
  },
  {
    id: "im_3",
    name: "Résidence Le Parc",
    address: "42 Boulevard Haussmann",
    city: "Paris",
    apartmentCount: 32,
  },
  {
    id: "im_4",
    name: "Les Terrasses",
    address: "3 Place de la République",
    city: "Marseille",
    apartmentCount: 16,
  },
];

export const mockAppartements = [
  {
    id: "ap_101",
    number: "A101",
    buildingId: "im_1",
    floor: 1,
    surface: 65,
    rooms: 3,
    status: "occupé",
  },
  {
    id: "ap_102",
    number: "A102",
    buildingId: "im_1",
    floor: 1,
    surface: 75,
    rooms: 4,
    status: "occupé",
  },
  {
    id: "ap_b201",
    number: "B201",
    buildingId: "im_2",
    floor: 2,
    surface: 55,
    rooms: 2,
    status: "vacant",
  },
  {
    id: "ap_c301",
    number: "C301",
    buildingId: "im_3",
    floor: 3,
    surface: 85,
    rooms: 4,
    status: "occupé",
  },
  {
    id: "ap_a205",
    number: "A205",
    buildingId: "im_4",
    floor: 2,
    surface: 70,
    rooms: 3,
    status: "occupé",
  },
];

export const mockResidents = [
  {
    id: "r_1",
    fullName: "Jean Dupont",
    email: "jean.dupont@email.com",
    phone: "06 12 34 56 78",
    apartmentId: "ap_101",
    entryDate: "15/01/2023",
  },
  {
    id: "r_2",
    fullName: "Marie Martin",
    email: "marie.martin@email.com",
    phone: "06 23 45 67 89",
    apartmentId: "ap_102",
    entryDate: "20/06/2022",
  },
  {
    id: "r_3",
    fullName: "Pierre Bernard",
    email: "pierre.bernard@email.com",
    phone: "06 34 56 78 90",
    apartmentId: "ap_c301",
    entryDate: "10/03/2023",
  },
  {
    id: "r_4",
    fullName: "Sophie Dubois",
    email: "sophie.dubois@email.com",
    phone: "06 45 67 89 01",
    apartmentId: "ap_a205",
    entryDate: "01/05/2023",
  },
];

export const mockPaiements = [
  {
    id: "p_1",
    residentId: "r_1",
    apartmentId: "ap_101",
    type: "Charges mensuelles",
    amount: 450,
    limitDate: "05/04/2026",
    status: "payé",
  },
  {
    id: "p_2",
    residentId: "r_2",
    apartmentId: "ap_102",
    type: "Charges mensuelles",
    amount: 520,
    limitDate: "05/04/2026",
    status: "en attente",
  },
  {
    id: "p_3",
    residentId: "r_3",
    apartmentId: "ap_c301",
    type: "Charges mensuelles",
    amount: 380,
    limitDate: "05/03/2026",
    status: "en retard",
  },
  {
    id: "p_4",
    residentId: "r_4",
    apartmentId: "ap_a205",
    type: "Charges mensuelles",
    amount: 490,
    limitDate: "05/04/2026",
    status: "payé",
  },
];

export const mockDepenses = [
  {
    id: "d_1",
    title: "Réparation ascenseur",
    buildingId: "im_1",
    category: "Maintenance",
    amount: 2500,
    date: "01/04/2026",
    description: "Réparation moteur ascenseur principal",
  },
  {
    id: "d_2",
    title: "Nettoyage menusel",
    buildingId: "im_2",
    category: "Entretien",
    amount: 800,
    date: "03/04/2026",
    description: "Service de nettoyage des parties communes",
  },
  {
    id: "d_3",
    title: "Électricité commune",
    buildingId: "im_3",
    category: "Utilités",
    amount: 450,
    date: "05/04/2026",
    description: "Facture électricité parties communes",
  },
  {
    id: "d_4",
    title: "Entretien espaces verts",
    buildingId: "im_4",
    category: "Jardinage",
    amount: 650,
    date: "06/04/2026",
    description: "Taille haies et tonte pelouse",
  },
];

